---
# Enable captive portal:
captive_portal:

# Enable webserver
web_server:
  port: 80
  css_url: https://kiln-controller.s3.eu-central-1.amazonaws.com/assets/index.css
  js_url: https://kiln-controller.s3.eu-central-1.amazonaws.com/assets/index.js

# Enable ota
ota:
  platform: esphome

# Enable logging
logger:
  level: INFO

# Enable status led on onboard led
status_led:
  pin:
    number: D2
    inverted: True

# Enable wifi
wifi:
  ap: {}
  fast_connect: true
  reboot_timeout: 0s

# Esphome setup
esphome:
  name: kiln

esp8266:
  board: d1_mini

# Modules setup
spi:
  miso_pin: D3
  clk_pin: D4

time:
  - platform: sntp
    id: sntp_time

# Setup API
kiln_api:
  time_id: sntp_time
external_components:
  - source: github://kiln-controller/esphome-kiln-api@main

# Kiln
output:
  - platform: slow_pwm
    id: heater
    period: 15s
    pin: D1

sensor:
  - platform: max6675
    name: Kiln Temperature
    id: kiln_temperature
    cs_pin: D5
    update_interval: 1s

climate:
  - platform: pid
    id: kiln  # DO NOT CHANGE: hardcoded referenced in kiln_api
    name: Kiln
    sensor: kiln_temperature
    default_target_temperature: "0"
    visual:
      min_temperature: 0
      max_temperature: 1500
      temperature_step: 0.1
    heat_output: heater
    deadband_parameters:
      threshold_high: 0.5°C
      threshold_low: -1.0°C
      kp_multiplier: 0.0   # proportional gain turned off inside deadband
      ki_multiplier: 0.05  # integral accumulates at only 5% of normal ki
      kd_multiplier: 0.0   # derviative is turned off inside deadband
      deadband_output_averaging_samples: 15   # average the output over 15 samples within the deadband

    # NOTE: update these after autotuning
    control_parameters:
      kp: 0.0
      ki: 0.0
      kd: 0.0
